## Heart Disease Dataset

https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset

1. age
2. sex
3. chest pain type (4 values)
4. resting blood pressure
5. serum cholestoral in mg/dl
6. fasting blood sugar > 120 mg/dl
7. resting electrocardiographic results (values 0,1,2)
8. maximum heart rate achieved
9. exercise induced angina
10. oldpeak = ST depression induced by exercise relative to rest
11. the slope of the peak exercise ST segment
12. number of major vessels (0-3) colored by flourosopy
13. thal: 0 = normal; 1 = fixed defect; 2 = reversable defect
14. target: the presence of heart disease in the patient. 0 = no disease; 1 = disease

심부전 발생여부 예측 : https://www.kaggle.com/datasets/andrewmvd/heart-failure-clinical-data

심혈관 질환 : https://www.kaggle.com/datasets/sulianova/cardiovascular-disease-dataset

## Load Dataset 데이터셋 로드

In [ ]:
%pip install pandas
%pip install matplotlib
%pip install seaborn
%pip install numpy
%pip install scikit-learn

In [3]:
import pandas as pd

df = pd.read_csv('./heart.csv')

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

### 데이터프레임 정보

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

### 유니크한 값

In [5]:
df.nunique()

age          41
sex           2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
dtype: int64

# Automatically Visualize Dataset 자동 시각화

AutoViz 설치

https://github.com/AutoViML/AutoViz

In [6]:
!pip install -q autoviz

In [7]:
%matplotlib inline

from autoviz.AutoViz_Class import AutoViz_Class
import matplotlib.pyplot as plt
plt.style.use('dark_background')

AV = AutoViz_Class()

AV.AutoViz(
    filename='',
    dfte=df,
    depVar='target',
    verbose=2, # 0: 간단히 표시; 1: 자세히 표시; 2: 파일로 저장
    max_rows_analyzed=df.shape[0],
    max_cols_analyzed=df.shape[1])

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Shape of your Data Set loaded: (1025, 14)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
  Printing up to 30 columns (max) in each category:
    Numeric Columns : ['oldpeak']
    Integer-Categorical Columns: ['age', 'cp', 'trestbps', 'chol', 'restecg', 'thalach', 'slope', 'ca', 'thal']
    String-Categorical Columns: []
    Factor-Categorical Columns: []
    String-Boolean Columns: []
    Numeric-Boolean Columns: ['sex', 'fbs', 'exang']
    Discrete String Columns: []
    NLP text Columns: []
    Date Time Columns: []
    ID Columns: []
    Columns that will not be considered in modeling: []
    13 Predictors classified...
        No variables removed since no ID or low-information variables found in data set
Since Number of Rows in data 1025 exceeds maximum, randomly sampling 1025 rows for EDA...

################ Binary_Classification problem #####################
   Columns to delete:
'   []'
   Boolean variables %s
"   ['sex', 'fbs', 'exang']"
   Categorical variables %s
("   ['age', 'cp', 'trestbps', 'chol', 'restecg', 'thalach', 'slope', 'ca', "
 "'thal', 'sex', 'fbs', 'exang']")
   Continuous variables %s
"   ['oldpeak']"
   Discrete string variables %s
'   []'
   Date and time variables %s
'   []'
   ID variables %s
'   []'
   Target variable %s
'   target'
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 723 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

All Plots are saved in ./AutoViz_Plots/target
Time to run AutoViz = 1 seconds

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
807,44,1,2,130,233,0,1,179,1,0.4,2,0,2,0
27,58,0,1,136,319,1,0,152,0,0.0,2,2,2,1
77,63,1,0,140,187,0,0,144,1,4.0,2,2,3,1
406,58,1,2,140,211,1,0,165,0,0.0,2,0,2,0
886,61,1,0,120,260,0,1,140,1,3.6,1,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,49,1,2,118,149,0,0,126,0,0.8,2,3,2,1
192,67,0,2,115,564,0,0,160,0,1.6,1,0,3,0
629,65,1,3,138,282,1,0,174,0,1.4,1,1,2,1
559,67,1,0,120,237,0,1,71,0,1.0,1,0,2,1
684,60,1,2,140,185,0,0,155,0,3.0,1,0,2,1

# LazyPredict

AutoML with scikit-learn

https://lazypredict.readthedocs.io/en/latest/

자동으로 베스트 모델 찾아주는 패키지

In [8]:
#!pip install scikit-learn==0.23.1
!pip install -q lazypredict

### 데이터 준비

In [9]:
y_data = df.pop('target')
x_data = df

print(x_data.shape)
print(y_data.shape)

(1025, 13)
(1025,)

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x_data,
    y_data,
    test_size=0.2,
    random_state=2022,
    stratify=y_data) # 클래스 비율을 동일하게 분할한다

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(820, 13) (820,)
(205, 13) (205,)

### 모델 성능 자동 비교

In [11]:
from lazypredict.Supervised import LazyClassifier

clf = LazyClassifier(verbose=0, predictions=True)

models, predictions = clf.fit(x_train, x_test, y_train, y_test)

models

 72%|███████▏  | 23/32 [00:00<00:00, 66.86it/s]

[LightGBM] [Info] Number of positive: 421, number of negative: 399
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000325 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 377
[LightGBM] [Info] Number of data points in the train set: 820, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.513415 -> initscore=0.053671
[LightGBM] [Info] Start training from score 0.053671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

100%|██████████| 32/32 [00:00<00:00, 37.01it/s]

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Time Taken
Model,,,,,
LGBMClassifier,1.00,1.00,1.00,1.00,0.44
DecisionTreeClassifier,1.00,1.00,1.00,1.00,0.00
ExtraTreeClassifier,1.00,1.00,1.00,1.00,0.00
ExtraTreesClassifier,1.00,1.00,1.00,1.00,0.05
RandomForestClassifier,1.00,1.00,1.00,1.00,0.06
LabelPropagation,1.00,1.00,1.00,1.00,0.01
LabelSpreading,1.00,1.00,1.00,1.00,0.01
BaggingClassifier,1.00,1.00,1.00,1.00,0.02
SVC,0.94,0.94,0.94,0.94,0.01
NuSVC,0.90,0.90,0.90,0.90,0.04
QuadraticDiscriminantAnalysis,0.89,0.89,0.89,0.89,0.01
GaussianNB,0.88,0.88,0.88,0.88,0.00
SGDClassifier,0.87,0.87,0.87,0.87,0.01
CalibratedClassifierCV,0.87,0.87,0.87,0.87,0.02
AdaBoostClassifier,0.87,0.87,0.87,0.87,0.06
LogisticRegression,0.86,0.86,0.86,0.86,0.00
LinearSVC,0.86,0.86,0.86,0.86,0.00
NearestCentroid,0.86,0.86,0.86,0.86,0.00
LinearDiscriminantAnalysis,0.86,0.86,0.86,0.86,0.01
RidgeClassifier,0.86,0.86,0.86,0.86,0.01
RidgeClassifierCV,0.86,0.86,0.86,0.86,0.00
BernoulliNB,0.85,0.85,0.85,0.85,0.01
KNeighborsClassifier,0.83,0.83,0.83,0.83,0.01
PassiveAggressiveClassifier,0.78,0.78,0.78,0.78,0.01
Perceptron,0.76,0.76,0.76,0.76,0.01
DummyClassifier,0.51,0.50,0.50,0.35,0.00

### 모델별 테스트 데이터 예측값

In [12]:
predictions.head()

,AdaBoostClassifier,BaggingClassifier,BernoulliNB,CalibratedClassifierCV,DecisionTreeClassifier,DummyClassifier,ExtraTreeClassifier,ExtraTreesClassifier,GaussianNB,KNeighborsClassifier,LabelPropagation,LabelSpreading,LinearDiscriminantAnalysis,LinearSVC,LogisticRegression,NearestCentroid,NuSVC,PassiveAggressiveClassifier,Perceptron,QuadraticDiscriminantAnalysis,RandomForestClassifier,RidgeClassifier,RidgeClassifierCV,SGDClassifier,SVC,LGBMClassifier
0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,1,0,1,1,0,1,0,0,1,1,0,0,1,1,1,1,1,1,1,0,0,1,1,1,0,0

### 모델별 분류 리포트

In [13]:
from sklearn.metrics import classification_report

for model_name in predictions.columns.tolist():
    print(f'{model_name}')
    print(classification_report(y_test, predictions[model_name]))

AdaBoostClassifier
              precision    recall  f1-score   support

           0       0.88      0.85      0.86       100
           1       0.86      0.89      0.87       105

    accuracy                           0.87       205
   macro avg       0.87      0.87      0.87       205
weighted avg       0.87      0.87      0.87       205

BaggingClassifier
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

BernoulliNB
              precision    recall  f1-score   support

           0       0.88      0.80      0.84       100
           1       0.82      0.90      0.86       105

    accuracy                           0.85       205
   macro avg       0.85      0.85      0.85       205
weighted avg       0.85      0.85      0.85       205

CalibratedClassifierCV
              precision    recall  f1-score   support

           0       0.95      0.78      0.86       100
           1       0.82      0.96      0.89       105

    accuracy                           0.87       205
   macro avg       0.89      0.87      0.87       205
weighted avg       0.88      0.87      0.87       205

DecisionTreeClassifier
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

DummyClassifier
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       100
           1       0.51      1.00      0.68       105

    accuracy                           0.51       205
   macro avg       0.26      0.50      0.34       205
weighted avg       0.26      0.51      0.35       205

ExtraTreeClassifier
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

ExtraTreesClassifier
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

GaussianNB
              precision    recall  f1-score   support

           0       0.89      0.85      0.87       100
           1       0.86      0.90      0.88       105

    accuracy                           0.88       205
   macro avg       0.88      0.88      0.88       205
weighted avg       0.88      0.88      0.88       205

KNeighborsClassifier
              precision    recall  f1-score   support

           0       0.85      0.80      0.82       100
           1       0.82      0.87      0.84       105

    accuracy                           0.83       205
   macro avg       0.84      0.83      0.83       205
weighted avg       0.84      0.83      0.83       205

LabelPropagation
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

LabelSpreading
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

LinearDiscriminantAnalysis
              precision    recall  f1-score   support

           0       0.96      0.74      0.84       100
           1       0.80      0.97      0.88       105

    accuracy                           0.86       205
   macro avg       0.88      0.86      0.86       205
weighted avg       0.88      0.86      0.86       205

LinearSVC
              precision    recall  f1-score   support

           0       0.95      0.76      0.84       100
           1       0.81      0.96      0.88       105

    accuracy                           0.86       205
   macro avg       0.88      0.86      0.86       205
weighted avg       0.88      0.86      0.86       205

LogisticRegression
              precision    recall  f1-score   support

           0       0.93      0.78      0.85       100
           1       0.82      0.94      0.88       105

    accuracy                           0.86       205
   macro avg       0.87      0.86      0.86       205
weighted avg       0.87      0.86      0.86       205

NearestCentroid
              precision    recall  f1-score   support

           0       0.94      0.76      0.84       100
           1       0.81      0.95      0.87       105

    accuracy                           0.86       205
   macro avg       0.87      0.86      0.86       205
weighted avg       0.87      0.86      0.86       205

NuSVC
              precision    recall  f1-score   support

           0       0.94      0.85      0.89       100
           1       0.87      0.95      0.91       105

    accuracy                           0.90       205
   macro avg       0.91      0.90      0.90       205
weighted avg       0.91      0.90      0.90       205

PassiveAggressiveClassifier
              precision    recall  f1-score   support

           0       0.77      0.77      0.77       100
           1       0.78      0.78      0.78       105

    accuracy                           0.78       205
   macro avg       0.78      0.78      0.78       205
weighted avg       0.78      0.78      0.78       205

Perceptron
              precision    recall  f1-score   support

           0       0.76      0.74      0.75       100
           1       0.76      0.77      0.76       105

    accuracy                           0.76       205
   macro avg       0.76      0.76      0.76       205
weighted avg       0.76      0.76      0.76       205

QuadraticDiscriminantAnalysis
              precision    recall  f1-score   support

           0       0.91      0.87      0.89       100
           1       0.88      0.91      0.90       105

    accuracy                           0.89       205
   macro avg       0.89      0.89      0.89       205
weighted avg       0.89      0.89      0.89       205

RandomForestClassifier
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

RidgeClassifier
              precision    recall  f1-score   support

           0       0.96      0.74      0.84       100
           1       0.80      0.97      0.88       105

    accuracy                           0.86       205
   macro avg       0.88      0.86      0.86       205
weighted avg       0.88      0.86      0.86       205

RidgeClassifierCV
              precision    recall  f1-score   support

           0       0.96      0.74      0.84       100
           1       0.80      0.97      0.88       105

    accuracy                           0.86       205
   macro avg       0.88      0.86      0.86       205
weighted avg       0.88      0.86      0.86       205

SGDClassifier
              precision    recall  f1-score   support

           0       0.91      0.82      0.86       100
           1       0.84      0.92      0.88       105

    accuracy                           0.87       205
   macro avg       0.88      0.87      0.87       205
weighted avg       0.88      0.87      0.87       205

SVC
              precision    recall  f1-score   support

           0       0.97      0.90      0.93       100
           1       0.91      0.97      0.94       105

    accuracy                           0.94       205
   macro avg       0.94      0.94      0.94       205
weighted avg       0.94      0.94      0.94       205

LGBMClassifier
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205

### 성능 좋은 LightGBM 사용

In [14]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score

lgbm = LGBMClassifier()

lgbm.fit(x_train, y_train)

y_pred = lgbm.predict(x_test)

accuracy_score(y_pred, y_test)

[LightGBM] [Info] Number of positive: 421, number of negative: 399
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000786 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 368
[LightGBM] [Info] Number of data points in the train set: 820, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.513415 -> initscore=0.053671
[LightGBM] [Info] Start training from score 0.053671
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

1.0

# 파라미터 자동 튜닝

### SVM 튜닝없이 돌렸을때

In [15]:
import numpy as np
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

X_train = pd.DataFrame(x_train)
X_test = pd.DataFrame(x_test)

pipe = Pipeline(steps=[
    ("preprocessor", StandardScaler()),
    ("classifier", SVC())
])

pipe.fit(x_train, y_train)

y_pred = pipe.predict(x_test)

accuracy_score(y_pred, y_test)

0.9365853658536586

In [16]:
pipe['classifier'].get_params()

{'C': 1.0,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

## Scikit-Optimize

Scikit-learn 의 머신러닝 모델들의 파라미터 자동 튜닝 패키지

https://scikit-optimize.github.io/stable/

In [17]:
!pip install -q scikit-optimize

In [18]:
from skopt import BayesSearchCV

pipe = Pipeline(steps=[
    ("preprocessor", StandardScaler()),
    ("classifier", SVC())
])

opt = BayesSearchCV(
    pipe,
    {
        'classifier__C': (1e-1, 1e+1, 'log-uniform'),
        'classifier__gamma': (1e-6, 1e+1, 'log-uniform'),
        'classifier__degree': (1, 8),  # integer valued parameter
        'classifier__kernel': ['linear', 'poly', 'rbf'],  # categorical parameter
    },
    n_iter=8,
    cv=3
)

opt.fit(x_train, y_train)

print("val. score: %s" % opt.best_score_)
print("test score: %s" % opt.score(x_test, y_test))

val. score: 0.9573139755621508
test score: 1.0

In [19]:
opt.best_params_

OrderedDict([('classifier__C', 0.5024634369465616),
             ('classifier__degree', 8),
             ('classifier__gamma', 3.345981143122703),
             ('classifier__kernel', 'poly')])